// Generates clone.sh + clone.ps1 for an assignment so the teacher can
// pull every student/team repo into a local folder. Re-runs `git pull`
// when a folder already exists.

import fs from 'node:fs/promises';
import path from 'node:path';
import {
  loadAssignment,
  readGroups,
  readRepos,
} from './lib/state.js';

const asgId = process.env.ASSIGNMENT_ID || process.argv[2];
const outDir = process.env.OUT_DIR || 'clone-out';
const [org] = (process.env.GITHUB_REPOSITORY || '').split('/');

if (!asgId) {
  console.error('Usage: ASSIGNMENT_ID=<id> node scripts/bulk-clone.js');
  process.exit(2);
}
if (!org) {
  console.error('Missing GITHUB_REPOSITORY (set to "<org>/<repo>")');
  process.exit(2);
}

function bashScript(repos) {
  const lines = [
    '#!/usr/bin/env bash',
    '# Auto-generated by classroom bulk-clone.',
    `# Assignment: ${asgId}`,
    `# Repo count: ${repos.length}`,
    'set -e',
    'mkdir -p "${1:-.}"',
    'cd "${1:-.}"',
    '',
  ];
  for (const r of repos) {
    const url = `https://github.com/${org}/${r.repo}.git`;
    lines.push(
      `echo "—— ${r.repo} (${r.label}) ——"`,
      `if [ -d "${r.repo}" ]; then`,
      `  ( cd "${r.repo}" && git pull --ff-only ) || echo "  (pull failed)"`,
      `else`,
      `  git clone "${url}" "${r.repo}" || echo "  (clone failed)"`,
      `fi`,
      '',
    );
  }
  return lines.join('\n');
}

function powershellScript(repos) {
  const lines = [
    '# Auto-generated by classroom bulk-clone.',
    `# Assignment: ${asgId}`,
    `# Repo count: ${repos.length}`,
    'param([string]$OutDir = ".")',
    '$ErrorActionPreference = "Continue"',
    'New-Item -ItemType Directory -Force -Path $OutDir | Out-Null',
    'Set-Location $OutDir',
    '',
  ];
  for (const r of repos) {
    const url = `https://github.com/${org}/${r.repo}.git`;
    lines.push(
      `Write-Host "—— ${r.repo} (${r.label}) ——"`,
      `if (Test-Path "${r.repo}") {`,
      `  Push-Location "${r.repo}"; git pull --ff-only; Pop-Location`,
      `} else {`,
      `  git clone "${url}" "${r.repo}"`,
      `}`,
      '',
    );
  }
  return lines.join('\r\n');
}

async function main() {
  const asg = await loadAssignment(asgId);
  let repos = [];
  if (asg.type === 'solo') {
    repos = (await readRepos(asgId)).map(r => ({ repo: r.repo, label: `@${r.student}` }));
  } else {
    repos = (await readGroups(asgId)).map(g => ({ repo: g.repo, label: `${g.slug}: ${g.members.map(m => '@' + m).join(', ')}` }));
  }
  if (!repos.length) {
    console.error(`No repos to clone for assignment "${asgId}".`);
    process.exit(1);
  }

  await fs.mkdir(outDir, { recursive: true });
  await fs.writeFile(path.join(outDir, 'clone.sh'), bashScript(repos), { encoding: 'utf8', mode: 0o755 });
  await fs.writeFile(path.join(outDir, 'clone.ps1'), powershellScript(repos), 'utf8');

  // Manifest for reference
  await fs.writeFile(
    path.join(outDir, 'manifest.json'),
    JSON.stringify({ assignment: asgId, generatedAt: new Date().toISOString(), repos }, null, 2),
  );

  console.log(`Generated ${repos.length} clone entries in ${outDir}/`);
  console.log(`  - clone.sh   (bash / git-bash / WSL / macOS / Linux)`);
  console.log(`  - clone.ps1  (PowerShell on Windows)`);
}

main().catch(e => {
  console.error(e);
  process.exit(1);
});
